project:
  type: website
  output-dir: docs

website:
  title: "timothy faust"
  #navbar:
    #left:
      #- href: index.qmd
        #text: Home
      #- about.qmd
  page-footer:
    left: 
      - text: "twitter"
        href: http://www.twitter.com/crulge
      - text: "email"
        href: mailto:tim.faust@gmail.com
    background: slateblue

format:
  html:
    theme: zephyr
    css: styles.css
    toc: false
